### ISSUE TITLE
Image namespace collision, breaks sync task

### ISSUE THREAD

**Issue by dpaola2** [desktoppr/giftoppr#11]
[https://github.com/desktoppr/giftoppr/blob/master/app/models/dropbox/uploader.rb#L17](https://github.com/desktoppr/giftoppr/blob/master/app/models/dropbox/uploader.rb#L17)

`Image` resolves to `Dropbox::Image` rather than the `Image` ActiveRecord model class. This makes the uploader fail during the sync task.

**Comment by keithpitt** [comment]
Hi, the sync task is working on production fine. What version of Ruby are you using?

**Comment by dpaola2** [comment]
Using ruby-1.9.3-p0. Here's what I get:

```
➜  giftoppr git:(master) bin/rake giftoppr:sync
WARNING: Nokogiri was built against LibXML version 2.9.0, but has dynamically loaded 2.7.8
rake aborted!
undefined method `find_by_unique_hash' for Dropbox::Image:Class
/Users/dpaola2/projects/giftoppr/app/models/dropbox/uploader.rb:17:in `upload_to_site'
/Users/dpaola2/projects/giftoppr/app/models/dropbox/uploader.rb:4:in `upload_to_site'
/Users/dpaola2/projects/giftoppr/app/models/dropbox/sync.rb:39:in `block in sync_and_return_cursor'
/Users/dpaola2/projects/giftoppr/app/models/dropbox/sync.rb:34:in `each'
/Users/dpaola2/projects/giftoppr/app/models/dropbox/sync.rb:34:in `sync_and_return_cursor'
/Users/dpaola2/projects/giftoppr/app/models/dropbox/sync.rb:13:in `sync_from_cursor'
/Users/dpaola2/projects/giftoppr/app/models/dropbox/sync.rb:4:in `sync_from_cursor'
/Users/dpaola2/projects/giftoppr/lib/tasks/giftoppr.rake:4:in `block (3 levels) in <top (required)>'
/Users/dpaola2/projects/giftoppr/lib/tasks/giftoppr.rake:3:in `each'
/Users/dpaola2/projects/giftoppr/lib/tasks/giftoppr.rake:3:in `block (2 levels) in <top (required)>'
Tasks: TOP => giftoppr:sync
(See full trace by running task with --trace)
➜  giftoppr git:(master) 

```

I've not changed anything except environment variables. What version of ruby do you run in production?

**Comment by mariovisic** [comment]
Odd; that method should be getting called on `::Image` and not `Dropbox::Image`. I think if you change it to explicitly be `::Image` it should work fine.

**Comment by dpaola2** [comment]
Yeah, that's why I opened a ticket. What version of ruby are you guys using?

**Comment by mariovisic** [comment]
2.0 I believe: https://github.com/desktoppr/giftoppr/blob/master/Gemfile#L3

**Comment by dpaola2** [comment]
Hm. Tried it with 2.0 and still no luck. I don't even know what else to try.

**Comment by mariovisic** [comment]
Can you try with bundler?

`bundle exec rake giftoppr:sync`

**Comment by keithpitt** [comment]
This is fixed in master!
