### ISSUE TITLE
Open Source Licence?

### ISSUE THREAD

**Issue by lukeholder** [desktoppr/giftoppr#9]
Hi, wondering what open source licence this is under? Could you please put it in the repo or readme? thanks.

**Comment by mariovisic** [comment]
I believe it'll be MIT, but i'm not 100% sure, will have to double check with @keithpitt

**Comment by keithpitt** [comment]
Yup, @mariovisic is right. I've added this: https://github.com/desktoppr/giftoppr/blob/master/LICENCE.txt
